package subconv

import (
	"net"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Clash renders a mihomo/Clash YAML config, merging the anti-leak template
// (dns/tun/sniffer/rules) with the generated proxies and a "Proxy" selector.
func Clash(proxies []*Proxy, template string) (string, error) {
	return clashWithProfile(proxies, template, ProfileLegacy)
}

// ClashWithProfile renders an explicitly selected routing profile. Clash keeps
// the old entry point separate so no-profile subscriptions remain byte-for-byte
// on the legacy path.
func ClashWithProfile(proxies []*Proxy, template string, profile RoutingProfile) (string, error) {
	return clashWithProfile(proxies, template, profile)
}

func clashWithProfile(proxies []*Proxy, template string, profile RoutingProfile) (string, error) {
	if strings.TrimSpace(template) == "" {
		template = DefaultClashTemplate
	}
	doc := map[string]any{}
	if err := yaml.Unmarshal([]byte(template), &doc); err != nil {
		doc = map[string]any{}
	}

	// Convert first, then dedupe the kept set so policy groups reference
	// unique, real node names (clashProxy drops unsupported protocols).
	type conv struct {
		m map[string]any
		p *Proxy
	}
	var cs []conv
	for _, p := range proxies {
		if m := clashProxy(p); m != nil {
			cs = append(cs, conv{m: m, p: p})
		}
	}
	kept := make([]*Proxy, len(cs))
	for i, c := range cs {
		kept[i] = c.p
	}
	dedupeNames(kept)
	list := make([]map[string]any, len(cs))
	for i, c := range cs {
		c.m["name"] = c.p.Name // sync after dedupe
		list[i] = c.m
	}
	doc["proxies"] = list
	sg := buildStrategyGroups(kept)
	doc["proxy-groups"] = mergeClashGroups(doc["proxy-groups"], clashGroups(sg), kept)
	if profile != ProfileLegacy {
		applyClashRoutingProfile(doc, profile)
	}
	if len(sg.ai) > 0 {
		injectClashAIRoute(doc)
	}
	// Always append the final catch-all referencing the ACTUAL primary group, so
	// the rule can never drift from the group name (templates must NOT hardcode
	// it — a stale "MATCH,<old name>" yields "proxy not found" in the client).
	rules, _ := doc["rules"].([]interface{})
	rules = append(rules, "MATCH,"+grpSelectClash)
	doc["rules"] = rules

	// Inject proxy server IPs into tun.route-exclude-address to prevent TUN
	// routing loop. These IPs are server-side data (the nodes we define), not
	// client-side config — the server knows its own node addresses.
	injectRouteExclude(doc, proxies)
	// Domain-based nodes can't be excluded by IP (route-exclude is CIDR-only, and
	// we don't know the resolved IP here). Instead pin their hostnames into
	// dns.fake-ip-filter so they always resolve to a real IP and stay outside the
	// tunnel via proxy-server-nameserver + auto-detect-interface.
	injectNodeDomains(doc, proxies)

	b, err := yaml.Marshal(doc)
	return string(b), err
}

var clashDomesticDNS = []any{
	"https://doh.pub/dns-query",
	"https://dns.alidns.com/dns-query",
}

// applyClashRoutingProfile replaces only the two managed CN rules. Admin rules
// such as ad rejection and private-network access keep their order and therefore
// still run first; the AI guard is injected afterwards and takes top priority.
//
// CN-direct also configures both query selection and direct-outbound resolution:
// nameserver-policy chooses a domestic DoH for CN queries, while
// direct-nameserver is what mihomo uses when a fake-IP domain is ultimately sent
// through DIRECT. The GEOIP rule is no-resolve so a foreign fake-IP domain is
// never resolved locally merely to test whether it is Chinese.
func applyClashRoutingProfile(doc map[string]any, profile RoutingProfile) {
	rules, _ := doc["rules"].([]any)
	kept := make([]any, 0, len(rules)+2)
	for _, raw := range rules {
		rule, ok := raw.(string)
		if ok && isManagedClashCNRule(rule) {
			continue
		}
		kept = append(kept, raw)
	}

	target := grpSelectClash
	if profile == ProfileCNDirect {
		target = "DIRECT"
	}
	kept = append(kept,
		"GEOSITE,CN,"+target,
		"GEOIP,CN,"+target+",no-resolve",
	)
	doc["rules"] = kept

	dns, _ := doc["dns"].(map[string]any)
	if dns == nil {
		dns = map[string]any{}
		doc["dns"] = dns
	}
	policy, _ := dns["nameserver-policy"].(map[string]any)
	if policy == nil {
		policy = map[string]any{}
		dns["nameserver-policy"] = policy
	}
	for key := range policy {
		if strings.EqualFold(strings.TrimSpace(key), "geosite:cn") {
			delete(policy, key)
		}
	}
	if profile == ProfileCNDirect {
		policy["geosite:cn"] = append([]any(nil), clashDomesticDNS...)
		dns["direct-nameserver"] = append([]any(nil), clashDomesticDNS...)
		dns["direct-nameserver-follow-policy"] = true
		return
	}
	// proxy-all must not inherit the CN resolver policy previously generated by
	// cn-direct if an administrator copied a rendered block into their template.
}

func isManagedClashCNRule(rule string) bool {
	parts := strings.Split(rule, ",")
	if len(parts) < 3 {
		return false
	}
	kind := strings.ToUpper(strings.TrimSpace(parts[0]))
	code := strings.ToUpper(strings.TrimSpace(parts[1]))
	return (kind == "GEOSITE" || kind == "GEOIP") && code == "CN"
}

// allPlaceholder is the token an admin writes inside a hand-written group's
// `proxies:` list to mean "every node in the subscription". A template cannot
// enumerate node names — they are generated per user, per render — so without
// it a custom group can only ever reference the built-in groups.
const allPlaceholder = "all"

PLACEHOLDER_WILL_REPLACE_REST
